[versions]
agp = "8.4.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
appcompat = "1.6.1"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
preference = "1.2.1"
unoloaderVersion = "24.2.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
libreoffice = { module = "org.libreoffice:libreoffice", version.ref = "unoloaderVersion" }
libreoffice-unoloader = { module = "org.libreoffice:unoloader", version.ref = "unoloaderVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

